sonar.projectKey=sanjayk36725_sutton-and-barto-from-scratch-1-bandits-and-dynamic-programming
sonar.organization=sanjayk36725
sonar.projectName=sutton-and-barto-from-scratch-1-bandits-and-dynamic-programming
sonar.sources=model.py
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py
sonar.python.version=3.10
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/__pycache__/**
